# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13641544e88947d1077331dd98d9ba7a578661587cfd118a60f7f2592809512aebadc5f7e3293eae43ca2511d7ca3bb6a5b0666b8bb496a6728bad401d80115c

test:
  secret_key_base: dc2999643d010f4754b8ee00c0863d84e261a46a1b9c52a176b20f9869700269c5668ffdd48f32cdab40b4298c3f4d2ed1a7a960d5b073963893e6a62142b804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
